# baseURL = "https://salopst.github.io/"
baseURL = "https://stephen.yearl.us/"
# baseURL = "http://localhost:1313/"

# enableRobotsTXT = true

title   = "yearl.us"
languageCode = "en-us"
theme = "hello-friend-ng"

PygmentsCodeFences = true
PygmentsStyle = "monokai"

paginate  = 25
rssLimit  = 25  # Maximum number of items in the RSS feed.
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License." # This message is only used by the RSS template.

 googleAnalytics = "UA-115768355-2"
 # https://www.google.com/recaptcha/admin/site/478495144/settings
 g_recaptcha_data_sitekey = "6LeoQYUcAAAAADkkd9v9JNkBd_aiVj7m4_lsvHaf"
 #disqusShortname = "usyearlsjy"

archetypeDir = "archetypes"
contentDir   = "content"
dataDir      = "data"
layoutDir    = "layouts"
# publishDir   = "public-static-hugo"

buildDrafts   = false
buildFuture   = false
buildExpired  = false
canonifyURLs  = true
timeout       = 20000 #10000 ms is default
enableRobotsTXT = true
enableGitInfo   = true
enableEmoji     = true
enableMissingTranslationPlaceholders = false
disableRSS     = false
disableSitemap = false
disable404     = false
disableHugoGeneratorInject = false

[permalinks]
  #posts = "/posts/:year/:month/:title/"
  # :slug defaults to :title if not present
  # so persistence w/ olde wordpresse site URLs!!
posts = ":slug/"

[author]
  name = "yearlus"

[markup]
  defaultMarkdownHandler = 'goldmark'
  [markup.asciidocExt]
    backend = 'html5'
    extensions = []
    failureLevel = 'fatal'
    noHeaderOrFooter = true
    preserveTOC = false
    safeMode = 'unsafe'
    sectionNumbers = false
    trace = false
    verbose = false
    workingFolderCurrent = false
    [markup.asciidocExt.attributes]

  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true

    [markup.goldmark.parser]
      autoHeadingID = true
      autoHeadingIDType = 'github'
      [markup.goldmark.parser.attribute]
        block = false
        title = true

    [markup.goldmark.renderer]
      hardWraps = false
      # set unsafe to true to allow includes in templates
      unsafe = true
      xhtml = false

[markupblackFriday]
  hrefTargetBlank = true
  footnoteAnchorPrefix = ""
  footnoteReturnLinkContents = ""

[taxonomies]
  tag      = "tags"
  category = "categories"
  series   = "series"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  # Metadata mostly used in document's head
  description = "A random personal rambling ported from Wordpress"
  keywords = "blog, Emacs, Hugo, technology, recipes, yearl"
  images = [""]

  homeSubtitle = "Nel mezzo del camin..."

  # sjy2 2021-09-18
  # this should be the goatcounter "code" https://goatcounter.com/
  # calls in the goatcounter.html template
  goatCounter = "yearlus"

  # Prefix of link to the git commit detail page. GitInfo must be enabled.
  gitUrl = "https://github.com/salopst"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Integrate Javascript files or stylesheets by adding the url to the external assets or by
  # linking local files with their path relative to the static folder, e.g. "/css/styles.css"
  customCSS = ["css/sjy-specials.css"]
  #customJS  = ["/js/mermaid.js"]

  # Toggle this option need to rebuild SCSS, requires extended version of Hugo
  justifyContent = false  # Set "text-align: justify" to .content.

  # Default theme "light" or "dark"
  defaultTheme = "dark"
  # themeColor = "#252627" # the theme default
  #  themeColor = "#223835" # that from olde wordpresse
    themeColor = "#2e3440" # Nord Polar Night 1

  # Colors for favicons
  [params.favicon.color]
  #  mask = "#252627"
  #  msapplication = "#252627"
  #  theme = "#252627"
    mask = "#2e3440"
    msapplication = "#2e3440"
    theme = "#2e3440"

  [params.logo]
    logoImage     = "/favicon_io/favicon-32x32.png"
    logoAlt       = "Home"
    #logoText     = " ~"
    #logoHomeLink = "/"
    # Set true to remove the logo cursor entirely.
    # logoCursorDisabled = true
    # Set to a valid CSS color to change the cursor in the logo.
     #logoCursorColor    = "#67a2c9"
     logoCursorColor    = "#8fbcbb" # Nord 8: https://www.nordtheme.com/
    # Set to a valid CSS time value to change the animation duration, "0s" to disable.
    # logoCursorAnimate  = "2s"

    [params.portrait]
      path = "/img/avatars/1200px-Salmo_trutta.png"
      alt = "Quick! Over the weir, lads!!"

    # Social icons
    [[params.social]]
      name = "twitter"
      url  = "https://twitter.com/salopst/"

    [[params.social]]
      name = "email"
      url  = "mailto:stephen@yearl.us"

    [[params.social]]
      name = "instagram"
      url  = "https://www.instagram.com/stephen.yearl/"

    #[[params.social]]
    #  name = "github"
    #  url  = "https://github.com/salopst"

    #[[params.social]]
    #  name = "linkedin"
    #  url  = "https://www.linkedin.com/"

   #[[params.social]]
   #  name = "stackoverflow"
   #  url  = "https://www.stackoverflow.com/"

[languages]
  [languages.en]
    #subtitle  = "Hello, friendo."
    weight    = 1
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'

  [languages.fr]
    #subtitle  = "Bonjour, mon ami."
    weight    = 2
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'

[languages.it]
    #subtitle  = "Ciao, amico!"
    weight    = 2
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'

[sitemap]
  changefreq = 'weekly'
  filename = 'sitemap.xml'
  priority = 0.5


[menu]
  [[menu.main]]
    identifier = "home"
    name       = "Home"
    url        = "/"
  [[menu.main]]
    identifier = "posts"
    name       = "Posts"
    url        = "posts/"
  [[menu.main]]
    identifier = "tag-cloud"
    name       = "Tags"
    url        = "tagcloud/"
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "about/"



### SIMPLE JS SEARCH
#
disableKinds = [ "taxonomy", "term" ]

# Search index for lunr.js
[outputFormats.SearchIndex]
    mediaType = "application/json"
    baseName = "search"
    isPlainText = false

[outputs]
home = [ "HTML", "RSS", "JSON", "SearchIndex"]
page = ["HTML"]

[params.search]
search = true
search_minify = true
